/**
 * @file CtaAngleDown
 * @author Auto Generated by IconGarden
 */

import cn from 'classnames';
import React from 'react';
import { TCommonIconProp } from '../../types';

export default ({
  size = 34,
  color,
  style = {},
  className = '',
}: TCommonIconProp) => (
  <span
    role="img"
    className={cn('icons', className)}
    style={{ color, ...style }}
  >
    <svg
      width={size}
      viewBox="0 0 34 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <g clipPath="url(#clip0_2_410)">
        <path
          d="M30 0H4C1.79086 0 0 1.79086 0 4V20C0 22.2091 1.79086 24 4 24H30C32.2091 24 34 22.2091 34 20V4C34 1.79086 32.2091 0 30 0Z"
          fill="black"
        />
        <path
          d="M21.8342 19.4082C25.8537 19.4082 29.1122 16.1497 29.1122 12.1301C29.1122 8.11055 25.8537 4.85205 21.8342 4.85205C17.8146 4.85205 14.5561 8.11055 14.5561 12.1301C14.5561 16.1497 17.8146 19.4082 21.8342 19.4082Z"
          fill="#F9A000"
        />
        <path
          d="M12.1301 19.4082C16.1496 19.4082 19.4081 16.1497 19.4081 12.1301C19.4081 8.11055 16.1496 4.85205 12.1301 4.85205C8.11054 4.85205 4.85205 8.11055 4.85205 12.1301C4.85205 16.1497 8.11054 19.4082 12.1301 19.4082Z"
          fill="#ED0006"
        />
        <path
          fillRule="evenodd"
          clipRule="evenodd"
          d="M16.9833 6.7063C18.4716 8.03893 19.4081 9.97515 19.4081 12.1301C19.4081 14.2851 18.4716 16.2213 16.9833 17.5539C15.4931 16.2222 14.5561 14.2856 14.5561 12.1301C14.5561 10.0399 15.4372 8.15557 16.8482 6.82814L16.9833 6.7063Z"
          fill="#FF5D00"
        />
      </g>
      <defs>
        <clipPath id="clip0_2_410">
          <rect width="34" height="24" fill="white" />
        </clipPath>
      </defs>
    </svg>
  </span>
);
