/**
 * @file CtaAngleDown
 * @author Auto Generated by IconGarden
 */

import cn from 'classnames';
import React from 'react';
import { TCommonIconProp } from '../../types';

export default ({
  size = 24,
  color,
  style = {},
  className = '',
}: TCommonIconProp) => (
  <span
    role="img"
    className={cn('icons spining', className)}
    style={{ color, ...style }}
  >
    <svg
      width={size}
      viewBox="0 0 24 24"
      fill="none"
      xmlns="http://www.w3.org/2000/svg"
    >
      <g clipPath="url(#clip0_1_370)">
        <path d="M10.5 1.5C10.5 0.670312 11.1703 0 12 0C18.6281 0 24 5.37188 24 12C24 14.1844 23.4141 16.2375 22.3922 18C21.9797 18.7172 21.0609 18.9609 20.3438 18.5484C19.6266 18.1359 19.3828 17.2172 19.7953 16.5C20.5594 15.1781 21 13.6406 21 12C21 7.03125 16.9688 3 12 3C11.1703 3 10.5 2.32969 10.5 1.5Z" />
        <path
          opacity="0.4"
          d="M12 3C7.03125 3 3 7.03125 3 12C3 16.9688 7.03125 21 12 21C15.2859 21 18.1547 19.2422 19.7297 16.6125L19.7344 16.6172C19.4109 17.3156 19.6641 18.1547 20.3438 18.5484C21.0609 18.9656 21.9797 18.7172 22.3922 18C22.4016 17.9859 22.4109 17.9719 22.4156 17.9578C20.3484 21.5672 16.4578 24 12 24C5.37188 24 0 18.6281 0 12C0 5.37188 5.37188 0 12 0C11.1703 0 10.5 0.670312 10.5 1.5C10.5 2.32969 11.1703 3 12 3Z"
        />
      </g>
      <defs>
        <clipPath id="clip0_1_370">
          <rect width="24" height="24" fill="white" />
        </clipPath>
      </defs>
    </svg>
  </span>
);
